name: thesis_pac_pipeline
version: "1.0.0"
config-version: 2

profile: thesis_pac_athena

model-paths:
  - models

macro-paths:
  - macros

test-paths:
  - tests

target-path: target

clean-targets:
  - target
  - dbt_packages

models:
  thesis_pac_pipeline:
    silver:
      +materialized: table
      +table_type: hive
      +format: parquet
      +tags:
        - silver
        - reference_parity

    intermediate:
      +materialized: ephemeral
      +tags:
        - intermediate

    gold:
      internal:
        +materialized: table
        +table_type: hive
        +format: parquet
        +schema: thesis_pac_dev_gold_internal
        +tags:
          - gold
          - internal
          - reference_parity

      public:
        +materialized: table
        +table_type: hive
        +format: parquet
        +schema: thesis_pac_dev_gold_public
        +tags:
          - gold
          - public
          - public_safe
          - reference_parity
